// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Echo",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Echo",
            targets: ["AppModule"],
            bundeIdentifier: "com.echomusic.app",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                
                .mediaLibrary(purposeString: "Used to add music from local files or Apple Music to Echo"),
                .bluetoothAlways(purposeString: "Used to connect to external devices like headphones or speakers")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
