name: Update SideStore Source

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: Widget # Vervang 'main' door 'Widget' als apps.json in de Widget branch moet staan

      - name: Generate apps.json
        run: |
          cat << 'EOF' > apps.json
      {
        "name": "Echo - MusicApp",
        "identifier": "com.echomusic.repo",
        "iconURL": "https://raw.githubusercontent.com/Seperatebugle21/Echo/Widget/Echo.swiftpm/Assets.xcassets/AppIcon.appiconset/AppIcon24.png",
        "apps": [
          {
            "name": "Echo",
            "bundleIdentifier": "com.echomusic.app",
            "developerName": "Seperatebugle21",
            "version": "1.0",
            "versionDate": "2026-09-19T22:10:45Z",
            "downloadURL": "https://github.com/Seperatebugle21/Echo/releases/download/v1.0/Echo.ipa",
            "localizedDescription": "The first release of Echo brings local music, podcasts, and audio discovery together in a native iPhone and iPad app built with Swift and SwiftUI.",
            "iconURL": "https://raw.githubusercontent.com/Seperatebugle21/Echo/Widget/Widget/Echo.swiftpm/Assets.xcassets/AppIcon.appiconset/AppIcon24.png",
            "tintColor": "007AFF",
            "size": ${{ github.event.release.assets[0].size }}
          }
        ]
      }
          EOF

      - name: Commit and Push apps.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add apps.json
          git commit -m "Update SideStore source for release ${{ github.event.release.tag_name }}" || exit 0
          git push origin HEAD:${{ github.event.repository.default_branch }}
